#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d  II III IV V VI VII

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config normal_border_color "#88C0D0"  # Border jendela normal
bspc config focused_border_color "#88C0D0" # Border jendela yang terfokus
bspc config active_border_color "#5E81AC"  # Border jendela yang sedang aktif
bspc config presel_border_color "#BF616A"  # Border preselection (untuk split window)
bspc config urgent_border_color "#D08770"  # Border jendela yang urgent (misal, notifikasi)
bspc config border_width 2                 # Lebar border (dalam pixel)

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#Autostart application
sxhkd &
polybar &
picom --config $HOME/.config/picom/picom.conf
feh --bg-fill ~/Downloads/59099_anime_girls_black_and_white_creepy_girl.jpg
dunst &

bspc subscribe node_state | while read -r _ _ state node_id; do
  if [ "$state" = "fullscreen" ]; then
    if bspc query -N -n "$node_id" >/dev/null; then
      polybar-msg cmd hide
    else
      polybar-msg cmd show
    fi
  fi
done &
